version: "3.8"

services:
  portfolio:
    build: .
    container_name: portfolio
    restart: unless-stopped

    labels:
      - "traefik.enable=true"

      # HTTP â†’ HTTPS
      - "traefik.http.routers.portfolio.entrypoints=web"
      - "traefik.http.routers.portfolio.rule=Host(`mmendol.com`,`www.mmendol.com`)"
      - "traefik.http.routers.portfolio.middlewares=redirect-to-https@docker"

      # HTTPS
      - "traefik.http.routers.portfolio-secure.entrypoints=websecure"
      - "traefik.http.routers.portfolio-secure.rule=Host(`mmendol.com`,`www.mmendol.com`)"
      - "traefik.http.routers.portfolio-secure.tls=true"
      - "traefik.http.routers.portfolio-secure.tls.certresolver=letsencrypt"

      # Porta interna do Nginx
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"

    networks:
      - proxy

networks:
  proxy:
    external: true
